/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMagazineCollage: typeof import('./src/components/about/AboutMagazineCollage.vue')['default']
    AboutSkillTree: typeof import('./src/components/about/AboutSkillTree.vue')['default']
    ApiButton: typeof import('./src/components/Api-Button.vue')['default']
    AppButton: typeof import('./src/components/ui/AppButton.vue')['default']
    AppConfigProvider: typeof import('./src/components/ui/AppConfigProvider.vue')['default']
    ArticleComments: typeof import('./src/components/article/ArticleComments.vue')['default']
    BackToTop: typeof import('./src/components/ui/BackToTop.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Card: typeof import('./src/components/ui/Card.vue')['default']
    CommentBox: typeof import('./src/components/ui/CommentBox.vue')['default']
    CommentItem: typeof import('./src/components/ui/CommentItem.vue')['default']
    DotGrid: typeof import('./src/components/DotGrid.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    EmojiReaction: typeof import('./src/components/reaction/EmojiReaction.vue')['default']
    EmoteDisplay: typeof import('./src/components/ui/EmoteDisplay.vue')['default']
    EmotePicker: typeof import('./src/components/ui/EmotePicker.vue')['default']
    EmoteRenderer: typeof import('./src/components/ui/EmoteRenderer.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    GalleryThumbnail: typeof import('./src/components/photo/GalleryThumbnail.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Icon: typeof import('./src/components/ui/Icon.vue')['default']
    IconCloud: typeof import('./src/components/ui/IconCloud.vue')['default']
    InfoPanel: typeof import('./src/components/photo/InfoPanel.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    LazyImage: typeof import('./src/components/photo/LazyImage.vue')['default']
    LivePhoto: typeof import('./src/components/photo/LivePhoto.vue')['default']
    LivePhotoIndicator: typeof import('./src/components/photo/LivePhotoIndicator.vue')['default']
    LivePhotoMute: typeof import('./src/components/photo/LivePhotoMute.vue')['default']
    Loading: typeof import('./src/components/ui/Loading.vue')['default']
    LoadingIndicator: typeof import('./src/components/photo/LoadingIndicator.vue')['default']
    LoginModal: typeof import('./src/components/auth/LoginModal.vue')['default']
    MagicCard: typeof import('./src/components/ui/MagicCard.vue')['default']
    Modal: typeof import('./src/components/ui/Modal.vue')['default']
    MomentCard: typeof import('./src/components/moment/MomentCard.vue')['default']
    PhotoLocationMap: typeof import('./src/components/photo/PhotoLocationMap.vue')['default']
    PhotoViewer: typeof import('./src/components/photo/PhotoViewer.vue')['default']
    PortfolioMagicCard: typeof import('./src/components/ui/PortfolioMagicCard.vue')['default']
    ProgressBar: typeof import('./src/components/ui/ProgressBar.vue')['default']
    ProgressiveImage: typeof import('./src/components/photo/ProgressiveImage.vue')['default']
    ProjectMagicCard: typeof import('./src/components/ui/ProjectMagicCard.vue')['default']
    RandomPortalButton: typeof import('./src/components/random/RandomPortalButton.vue')['default']
    ReactionConfetti: typeof import('./src/components/reaction/ReactionConfetti.vue')['default']
    RichTextarea: typeof import('./src/components/ui/RichTextarea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareModal: typeof import('./src/components/photo/ShareModal.vue')['default']
    SparklesText: typeof import('./src/components/ui/SparklesText.vue')['default']
    SplitText: typeof import('./src/components/SplitText.vue')['default']
    TenYearPromise: typeof import('./src/components/ui/TenYearPromise.vue')['default']
    ThemeToggle: typeof import('./src/components/ui/ThemeToggle.vue')['default']
    ThumbHash: typeof import('./src/components/ui/ThumbHash.vue')['default']
    Timeline: typeof import('./src/components/ui/Timeline.vue')['default']
    UButton: typeof import('./src/components/ui/UButton.vue')['default']
    VideoPlayer: typeof import('./src/components/ui/VideoPlayer.vue')['default']
    VisitorPassportCard: typeof import('./src/components/guestbook/VisitorPassportCard.vue')['default']
  }
}
