/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiButton: typeof import('./src/components/Api-Button.vue')['default']
    Background: typeof import('./src/components/widgets/Background.vue')['default']
    Border: typeof import('./src/components/widgets/Border.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Card: typeof import('./src/components/ui/Card.vue')['default']
    DotGrid: typeof import('./src/components/DotGrid.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmojiReaction: typeof import('./src/components/EmojiReaction.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    MagicCard: typeof import('./src/components/ui/MagicCard.vue')['default']
    Modal: typeof import('./src/components/ui/Modal.vue')['default']
    PortfolioMagicCard: typeof import('./src/components/ui/PortfolioMagicCard.vue')['default']
    ProgressBar: typeof import('./src/components/ui/ProgressBar.vue')['default']
    ProjectMagicCard: typeof import('./src/components/ui/ProjectMagicCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitText: typeof import('./src/components/SplitText.vue')['default']
    TenYearPromise: typeof import('./src/components/ui/TenYearPromise.vue')['default']
    ThemeToggle: typeof import('./src/components/ui/ThemeToggle.vue')['default']
    VueColorAvatar: typeof import('./src/components/VueColorAvatar.vue')['default']
  }
}
