/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Card: typeof import('./src/components/ui/Card.vue')['default']
    DotGrid: typeof import('./src/components/DotGrid.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    MagicCard: typeof import('./src/components/ui/MagicCard.vue')['default']
    Modal: typeof import('./src/components/ui/Modal.vue')['default']
    PortfolioMagicCard: typeof import('./src/components/ui/PortfolioMagicCard.vue')['default']
    ProgressBar: typeof import('./src/components/ui/ProgressBar.vue')['default']
    ProjectMagicCard: typeof import('./src/components/ui/ProjectMagicCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitText: typeof import('./src/components/SplitText.vue')['default']
    TenYearPromise: typeof import('./src/components/ui/TenYearPromise.vue')['default']
    ThemeToggle: typeof import('./src/components/ui/ThemeToggle.vue')['default']
  }
}
